# Generated by Django 4.2.11 on 2024-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
