# Generated by Django 4.2.11 on 2024-05-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='product title', max_length=70)),
                ('product_Ingredient', models.CharField(default='Ingredient', max_length=150)),
                ('product_price', models.PositiveIntegerField(default=0)),
                ('product_cat_id', models.PositiveIntegerField(default=0)),
                ('product_fav', models.BooleanField(default=False)),
                ('product_picture', models.ImageField(default='', upload_to='products/')),
            ],
        ),
    ]
