# Generated by Django 4.2.11 on 2024-05-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_category_category_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='product_category_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.category'),
        ),
    ]
